# Generated by Django 3.1.3 on 2021-06-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='tarefa',
        ),
    ]
